### ISSUE TITLE
tensorflow 2.8.0 has no comapt function

### ISSUE THREAD

**Issue by wangzwYYDS** [hkimlab/DeepPrime#9]
I install the software by conda  and source code, tensorflow =2.8.0  , then I run the example . not work

**Comment by wangzwYYDS** [comment]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "***/dprime/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "***/miniconda32024/envs/dprime/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "***/Custom/DeepPrime-main/DeepPrime.py", line 95, in worker
    else: result, DPStop4 = deep_prime(sample_name, sID, Ref_seq, ED_seq, sAlt, out_dir, dict_params)
  File "***/Custom/DeepPrime-main/DeepPrime.py", line 167, in deep_prime
    df['DeepSpCas9_score'] = calculate_DeepSpCas9_score(os.getcwd(), list_Guide30)
  File "***/Custom/DeepPrime-main/src/dspcas9.py", line 146, in calculate_DeepSpCas9_score
    sess.run(tf.comapt.v1.global_variables_initializer())
AttributeError: module 'tensorflow' has no attribute 'comapt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "***/Custom/DeepPrime-main/DeepPrime.py", line 270, in <module>
    deepprime_pipeline(input_file, sample_name, pe_type, cell_type, pbs_min, pbs_max, jobs, progress)
  File "***/Custom/DeepPrime-main/DeepPrime.py", line 58, in deepprime_pipeline
    p.map_async(worker, list_sParameters).get()
  File "***/miniconda32024/envs/dprime/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: module 'tensorflow' has no attribute 'comapt'

**Comment by Goosang-Yu** [comment]
Dear @wangzwYYDS 

Thank you for sharing the important details.
The issue occurred due to a bug in the code.

It has been fixed in the commit below:
99272383d1420576551d271d865b9972a63466c0

Please download the latest source code and check again.
Thank you
